### ISSUE TITLE
How to use your code example? 

### ISSUE THREAD

**Issue by IncByteLC** [ibotty/wp-post-merge#4]
How to use your code example? Should it be in function.php? (It's not working for me)
```
# add a field to posts
function my_add_foobar($post) {
  $post->foobar = _amzaff_prodid ($post);
  return $post;
}
```

**Comment by ibotty** [comment]
I assume the plugin does not work at all anymore.  The project is abandoned by me for 11 years at that point.  Sorry.  I'll archive the project to make that clear.
